services:
    postgres:
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
        container_name: postgres-mychat
        hostname: postgres-mychat
        image: pgvector/pgvector:pg16
        ports:
            - 5432:5432
        volumes:
            - pg:/var/lib/postgresql/data
        env_file:
            - .env

    mychat:
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
        image: jedwards1230/mychat:latest
        container_name: mychat
        hostname: mychat
        ports:
            - 3000:3000
        depends_on:
            - postgres
        env_file:
            - .env
        environment:
            - DB_HOST=postgres

volumes:
    pg: