services:
    postgres:
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
        container_name: postgres-mychat
        image: postgres:latest
        volumes:
            - ./docker-service/pg/:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - mychat

    mychat:
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
        image: jedwards1230/mychat:latest
        container_name: mychat
        ports:
            - 3000:3000
        depends_on:
            - postgres
        env_file:
            - .env
        environment:
            - DB_HOST=postgres
        networks:
            - mychat

    mindsdb:
        image: mindsdb/mindsdb
        container_name: mindsdb
        depends_on:
            - postgres
        ports:
            - 47334:47334
            - 47335:47335
        volumes:
            - ./docker-service/mindsdb:/root/mdb_storage
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
        networks:
            - mychat

networks:
    mychat:
