services:
    postgres:
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
        container_name: postgres-mychat
        image: pgvector/pgvector:pg16
        depends_on:
            - tailscale
        volumes:
            - pg:/var/lib/postgresql/data
        env_file:
            - .env
        network_mode: service:tailscale

    mindsdb:
        image: mindsdb/mindsdb
        container_name: mindsdb
        volumes:
            - mindsdb:/root
        depends_on:
            - tailscale
        network_mode: service:tailscale
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3

    mychat:
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
        image: jedwards1230/mychat:latest
        container_name: mychat
        depends_on:
            - postgres
            - tailscale
        env_file:
            - .env
        network_mode: service:tailscale

    tailscale:
        deploy:
            restart_policy:
                condition: on-failure
                delay: 3s
                max_attempts: 3
            resources:
                limits:
                    cpus: "0.50"
                    memory: 1G
        image: tailscale/tailscale:latest
        hostname: mychat
        container_name: tailscale-mychat
        # exposing ports here is useful for local network management
        # mostly for testing outside of the tailscale network
        #ports:
        # optionally expose mindsdb ports
        #- 47334:47334
        #- 47335:47335
        # optionally expose postgres ports
        #- 5432:5432
        # optionally expose mychat ports
        #- 3050:3050
        environment:
            - TS_ACCEPT_DNS=true
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_SERVE_CONFIG=/config/funnel.json
            - TS_USERSPACE=false
        env_file:
            - .env
        volumes:
            - ts:/var/lib/tailscale
            - ${PWD}/config:/config
            #- /dev/net/tun:/dev/net/tun
        cap_add:
            - net_admin
            - sys_module

volumes:
    pg:
    mindsdb:
    ts:
