name: Build and Push Docker Image

on:
    push:
        branches: ["actions"]
    pull_request:
        branches: ["actions"]

jobs:
    compile-client:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Cache node modules
              id: cache-node
              uses: actions/cache@v3
              with:
                  path: ./client/node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('./client/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            - name: Install client dependencies
              if: steps.cache-node.outputs.cache-hit != 'true'
              working-directory: ./client
              run: npm install --legacy-peer-deps

            - name: Export client
              working-directory: ./client
              run: npm run export # create static files in ./client/dist. this directory and relative path is needed by the dockerfile

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: ./client/dist

    compile-server:
        needs: compile-client
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: ./client/dist

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: ${{ github.repository }}:latest
