name: Build and Push Docker Image

on:
    workflow_run:
        workflows: ["Install and Compile Client"]
        types:
            - completed

jobs:
    compile-server:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: ./client/dist

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: downcase REPO
              id: repo_name
              run: |
                  echo "REPO=${GITHUB_REPOSITORY@L}" >> "$GITHUB_OUTPUT"
                  ls -la

            - name: Build and push
              uses: docker/build-push-action@v5
              env:
                  REPO: ${{steps.repo_name.outputs.REPO}}
              with:
                  push: true
                  tags: ${{env.REPO}}:latest
