name: CI

on:
    push:
        branches: ["main", "dev", "add-nextjs"]

jobs:
    build:
        name: Build and Push
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Get repo details
              id: repo_details
              run: |
                  echo "REPO=${GITHUB_REPOSITORY@L}" >> "$GITHUB_OUTPUT"
                  echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
                  echo "REPO_URL=https://github.com/${{ github.repository }}" >> "$GITHUB_OUTPUT"
                  echo "IMAGE_TAG=${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}" >> "$GITHUB_OUTPUT"

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  platforms: linux/arm64
                  push: true
                  tags: ${{ steps.repo_details.outputs.REPO }}:${{ steps.repo_details.outputs.IMAGE_TAG }}
                  file: docker/Dockerfile
                  build-args: |
                      COMMIT_HASH=${{ steps.repo_details.outputs.COMMIT_HASH }}
                      REPO_URL=${{ steps.repo_details.outputs.REPO_URL }}
                      TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
                      TURBO_TEAM=${{ secrets.TURBO_TEAM }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
